#!/usr/bin/env bash
# generated by bi_generate.py — regenerated on re-learn; do not hand-edit
# deterministic domain-logic drift check for province 'citadel-home'
set -euo pipefail
ROOT="${1:-$(pwd)}"
exec python "$(dirname "$0")/../tools/generated/logic_validate_citadel-home.py" "$ROOT"

