#!/usr/bin/env python3
"""bi_generate.py — turn learned domain logic into live capabilities (the self-improving part).

The Cartographer learns; this generates. From a province's `understanding` (units + vocab + scorecard) it
emits, **template-driven and agnostic** (no domain terms in the templates — they are filled per-province):

- a **brain node** per unit          docs/brain/nodes/domain/logic/<province>/<unit>.md
- a **review skill**                 .claude/skills/logic-review-<province>/SKILL.md
- a **validation workflow**          docs/brain/nodes/workflows/logic-validation-<province>.md
- a deterministic **validator tool** tools/generated/logic_validate_<province>.py
- a **script** wrapper               scripts/logic-<province>-check.sh

Generation is deterministic + idempotent: re-running produces byte-identical output, so an artifact stays in
sync with what was learned. Generated files are regenerated (not hand-edited); the memory `.md` (Cartographer)
is the one place user edits are preserved.
"""

import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

_GEN_BANNER = "<!-- generated by bi_generate.py — regenerated on re-learn; do not hand-edit -->"


def _slug(name: str) -> str:
    import re

    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-") or "unit"


def node_md(province: str, unit: dict) -> str:
    ev = unit.get("evidence", [])
    src = ev[0] if ev else {}
    links = sorted({e.get("source_path", "") for e in ev if e.get("source_path")})
    front = [
        "---",
        "node_type: domain-logic",
        f"province: {province}",
        f"unit: {unit['name']}",
        f"kind: {unit['kind']}",
        f"confidence: {unit.get('confidence', 0)}",
        f"content_hash: {unit.get('content_hash', '')}",
        "links:",
        *[f"  - {p}" for p in links],
        "---",
    ]
    body = [
        "",
        _GEN_BANNER,
        f"# {unit['name']} ({unit['kind']})",
        "",
        f"Learned from this province with confidence **{unit.get('confidence', 0)}**.",
        "",
        f"- primary source: `{src.get('source_path', '?')}`"
        + (f" line {src['line']}" if src.get("line") else ""),
        f"- evidence: {len(ev)} record(s) across {len(links)} file(s)",
        "",
        "## Evidence",
        *[f"- `{e.get('source_path', '?')}`:{e.get('line', 0)} — {e.get('snippet', '')[:100]}" for e in ev[:8]],
        "",
    ]
    return "\n".join(front + body) + "\n"


def skill_md(province: str, units: list[dict]) -> str:
    checks = [f"- `{u['name']}` ({u['kind']}, confidence {u.get('confidence', 0)})" for u in units[:40]]
    return "\n".join([
        "---",
        f"name: logic-review-{province}",
        f"description: Review a change against {province}'s learned domain logic ({len(units)} units).",
        "---",
        "",
        _GEN_BANNER,
        f"# Logic review — {province}",
        "",
        "When a change touches this province's domain logic, verify each affected unit still holds: its",
        "definition, inputs, and expected behavior match what was learned. Learned units:",
        "",
        *checks,
        "",
        "Run the generated validator for a deterministic drift check:",
        f"`scripts/logic-{province}-check.sh`",
        "",
    ]) + "\n"


def workflow_md(province: str, units: list[dict]) -> str:
    return "\n".join([
        "---",
        "node_type: workflow",
        f"name: logic-validation-{province}",
        f"province: {province}",
        "---",
        "",
        _GEN_BANNER,
        f"# Logic validation workflow — {province}",
        "",
        f"Gate for changes touching {province}'s domain logic ({len(units)} units):",
        "",
        f"1. Run `tools/generated/logic_validate_{province}.py` — detects added/removed/changed units.",
        f"2. For any changed unit, run the `logic-review-{province}` skill.",
        "3. A change that alters a high-confidence unit requires a not-self validation quorum (Pandidakterion).",
        "",
    ]) + "\n"


def validator_py(province: str) -> str:
    """A self-contained, deterministic drift detector: re-learn the province and diff against the persisted
    units.json — exit 1 on drift. Agnostic: it names no domain terms, only reads what was learned."""
    return f'''#!/usr/bin/env python3
# generated by bi_generate.py — regenerated on re-learn; do not hand-edit
"""logic_validate_{province}.py — generated drift detector for province '{province}' (deterministic, T0)."""
import json
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parents[1]
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))
from bi_cartographer import learn, state_dir  # noqa: E402


def main() -> int:
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    persisted = state_dir(root, "{province}") / "units.json"
    if not persisted.exists():
        print("no baseline units.json — run the Cartographer first"); return 0
    old = {{u["name"]: u.get("content_hash", "") for u in json.loads(persisted.read_text(encoding="utf-8"))}}
    fresh = {{u["name"]: u.get("content_hash", "") for u in learn(root, province="{province}", write=False)["units"]}}
    added = sorted(set(fresh) - set(old))
    removed = sorted(set(old) - set(fresh))
    changed = sorted(n for n in set(old) & set(fresh) if old[n] != fresh[n])
    for label, items in (("added", added), ("removed", removed), ("changed", changed)):
        for n in items:
            print(f"[{{label}}] {{n}}")
    drift = bool(added or removed or changed)
    verdict = "yes" if drift else "none"
    print(f"drift: {{verdict}} ({{len(added)}} added, {{len(removed)}} removed, {{len(changed)}} changed)")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
'''


def script_sh(province: str) -> str:
    return "\n".join([
        "#!/usr/bin/env bash",
        "# generated by bi_generate.py — regenerated on re-learn; do not hand-edit",
        f"# deterministic domain-logic drift check for province '{province}'",
        'set -euo pipefail',
        'ROOT="${1:-$(pwd)}"',
        f'exec python "$(dirname "$0")/../tools/generated/logic_validate_{province}.py" "$ROOT"',
        "",
    ]) + "\n"


def _write_if_changed(path: Path, content: str) -> None:
    """Write generated content only when bytes differ, preserving stable mtimes."""
    try:
        if path.read_text(encoding="utf-8") == content:
            return
    except OSError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate(root: str | Path, understanding: dict, *, write: bool = True, min_confidence: float = 0.4) -> dict:
    """Emit all artifacts for a province's understanding. Returns {kind: [paths]}."""
    root = Path(root).resolve()
    province = understanding["province"]
    units = [u for u in understanding["units"] if u.get("confidence", 0) >= min_confidence]
    slug_p = _slug(province)
    outputs: dict[str, list[str]] = {"nodes": [], "skill": [], "workflow": [], "validator": [], "script": []}

    node_dir = root / "docs" / "brain" / "nodes" / "domain" / "logic" / province
    files: list[tuple[Path, str, str]] = []
    for u in units:
        files.append((node_dir / f"{_slug(u['name'])}.md", node_md(province, u), "nodes"))
    files.append((root / ".claude" / "skills" / f"logic-review-{slug_p}" / "SKILL.md",
                  skill_md(province, units), "skill"))
    files.append((root / "docs" / "brain" / "nodes" / "workflows" / f"logic-validation-{slug_p}.md",
                  workflow_md(province, units), "workflow"))
    files.append((root / "tools" / "generated" / f"logic_validate_{slug_p}.py",
                  validator_py(slug_p), "validator"))
    files.append((root / "scripts" / f"logic-{slug_p}-check.sh", script_sh(slug_p), "script"))

    for path, content, kind in files:
        if write:
            _write_if_changed(path, content)
        outputs[kind].append(str(path.relative_to(root)) if path.is_relative_to(root) else str(path))
    return outputs


def main() -> None:
    import argparse

    from bi_cartographer import learn

    ap = argparse.ArgumentParser(description="Generate live capabilities from a province's learned logic.")
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--province", default=None)
    args = ap.parse_args()
    understanding = learn(args.root, province=args.province, write=True)
    outputs = generate(args.root, understanding)
    print(json.dumps({k: len(v) for k, v in outputs.items()}, indent=2))


if __name__ == "__main__":
    main()
