#!/usr/bin/env python3
"""bi_sources.py — multi-source, agnostic evidence extraction for the Cartographer (Pandidakterion Grammar).

The "Grammar" stage of the curriculum: read a province's own artifacts and emit **evidence records** for the
*domain-logic units* it defines — metrics, rules, transforms, policies. Nothing domain-specific is shipped;
units are found by **structure** (aggregations, boolean gates, GROUP BY, glossary rows, declared keys), so
two different provinces yield two different vocabularies. Every extractor is deterministic and zero-token.

An Evidence record is one atom: `{unit, kind, source_path, line, weight, snippet}`. Synthesis assembles them
into units with confidence.
"""

import ast
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path

# structural signals — NOT domain vocabulary. Presence of these constructs marks a logic unit by KIND.
_AGG_CALLS = frozenset({"sum", "mean", "avg", "average", "count", "min", "max", "median", "std",
                        "groupby", "agg", "aggregate", "pivot", "rollup", "ratio", "rate", "cumsum"})
_RULE_HINTS = re.compile(r"(?i)\b(validate|check|assert|rule|policy|guard|enforce|must|require|constraint)\w*")
_TRANSFORM_HINTS = re.compile(r"(?i)\b(transform|normalize|clean|map|convert|derive|compute|encode|parse)\w*")
_CODE_EXT = {".py"}
_SQL_EXT = {".sql"}
_DOC_EXT = {".md", ".markdown", ".rst"}
_CFG_EXT = {".yaml", ".yml", ".json", ".toml"}
_IGNORE_PARTS = {".git", ".venv", "__pycache__", "node_modules", ".citadel", "site-packages", ".claude", "generated"}
# markers stamped into Cartographer-generated artifacts — never ingest our own output (no phantom units)
_GENERATED_MARKERS = ("generated by bi_generate.py", "CARTOGRAPHER:BEGIN (generated")


@dataclass(slots=True)
class Evidence:
    unit: str
    kind: str          # metric | rule | transform | policy | term
    source_path: str
    line: int
    weight: float
    snippet: str

    def to_dict(self) -> dict:
        return asdict(self)


def _snippet(text: str, n: int = 140) -> str:
    return re.sub(r"\s+", " ", (text or "")).strip()[:n]


def _calls_in(node: ast.AST) -> set[str]:
    out: set[str] = set()
    for sub in ast.walk(node):
        if isinstance(sub, ast.Call):
            fn = sub.func
            name = getattr(fn, "attr", None) or getattr(fn, "id", None)
            if name:
                out.add(name.lower())
    return out


def extract_from_python(path: str, text: str) -> list[Evidence]:
    """A function is a logic unit when its body aggregates (metric), gates (rule/policy), or transforms."""
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    out: list[Evidence] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        calls = _calls_in(node)
        name = node.name
        snippet = _snippet(ast.get_source_segment(text, node) or name)
        if calls & _AGG_CALLS:
            out.append(Evidence(name, "metric", path, node.lineno, 1.0, snippet))
        elif _RULE_HINTS.search(name):
            kind = "policy" if re.search(r"(?i)policy|enforce|must|require", name) else "rule"
            out.append(Evidence(name, kind, path, node.lineno, 0.8, snippet))
        elif _TRANSFORM_HINTS.search(name):
            out.append(Evidence(name, "transform", path, node.lineno, 0.7, snippet))
    return out


_SQL_GROUPBY = re.compile(r"(?is)\bgroup\s+by\b(.+?)(?:\border\s+by\b|\bhaving\b|;|$)")
_SQL_VIEW = re.compile(r"(?is)\bcreate\s+(?:or\s+replace\s+)?(?:materialized\s+)?view\s+([A-Za-z_][\w.]*)")


def extract_from_sql(path: str, text: str) -> list[Evidence]:
    """GROUP BY marks a metric's grain; a view/CTE name is the unit's handle."""
    out: list[Evidence] = []
    for m in _SQL_VIEW.finditer(text):
        line = text[: m.start()].count("\n") + 1
        out.append(Evidence(m.group(1).split(".")[-1], "metric", path, line, 0.9, _snippet(m.group(0))))
    for m in _SQL_GROUPBY.finditer(text):
        line = text[: m.start()].count("\n") + 1
        grain = _snippet(m.group(1), 80)
        out.append(Evidence(f"grain::{grain}", "metric", path, line, 0.6, _snippet("GROUP BY " + grain)))
    return out


_MD_DEF = re.compile(r"^\s*[-*]?\s*\*{0,2}([A-Z][\w ./-]{1,40}?)\*{0,2}\s*[:：]\s+(.{8,})$")  # noqa: RUF001 — fullwidth colon is intentional (i18n docs)
_MD_TABLE = re.compile(r"^\s*\|\s*([A-Za-z][\w ./-]{1,40}?)\s*\|\s*(.{4,}?)\s*\|")


def extract_from_markdown(path: str, text: str) -> list[Evidence]:
    """Glossary/KPI rows (`**Term**: definition` or table `| term | definition |`) are declared units."""
    out: list[Evidence] = []
    for i, raw in enumerate(text.splitlines(), start=1):
        for pat in (_MD_DEF, _MD_TABLE):
            m = pat.match(raw)
            if m and not m.group(1).lower().startswith(("http", "note", "warning", "example")):
                out.append(Evidence(m.group(1).strip(), "term", path, i, 0.5, _snippet(raw)))
                break
    return out


def extract_from_config(path: str, text: str) -> list[Evidence]:
    """Keys nested under a metrics/rules/dimensions/policies section are declared units (structural)."""
    out: list[Evidence] = []
    section = re.compile(r"(?i)\b(metric|rule|dimension|policy|measure|kpi|transform)s?\b")
    current = None
    for i, raw in enumerate(text.splitlines(), start=1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip())
        key_match = re.match(r"[\"']?([A-Za-z_][\w .-]{1,40})[\"']?\s*[:=]", stripped)
        if indent == 0 and key_match and section.search(key_match.group(1)):
            current = key_match.group(1)
            continue
        if current and indent > 0 and key_match:
            kind = "rule" if "rule" in current.lower() or "policy" in current.lower() else "metric"
            out.append(Evidence(key_match.group(1).strip(), kind, path, i, 0.6, _snippet(stripped)))
    return out


_DISPATCH = [
    (_CODE_EXT, extract_from_python),
    (_SQL_EXT, extract_from_sql),
    (_DOC_EXT, extract_from_markdown),
    (_CFG_EXT, extract_from_config),
]


def _extractor_for(suffix: str):
    for exts, fn in _DISPATCH:
        if suffix.lower() in exts:
            return fn
    return None


def ingest(root: str | Path, *, max_files: int = 5000, max_bytes: int = 512 * 1024) -> list[Evidence]:
    """Walk a province root and emit evidence from every recognized file. Deterministic, zero-token."""
    root = Path(root)
    evidence: list[Evidence] = []
    seen = 0
    for path in sorted(root.rglob("*")):
        if seen >= max_files:
            break
        if not path.is_file() or any(part in _IGNORE_PARTS for part in path.parts):
            continue
        fn = _extractor_for(path.suffix)
        if fn is None:
            continue
        try:
            if path.stat().st_size > max_bytes:
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if any(marker in text for marker in _GENERATED_MARKERS):
            continue  # skip Cartographer-generated artifacts (self-ingestion → phantom units)
        seen += 1
        rel = str(path.relative_to(root)) if path.is_relative_to(root) else str(path)
        evidence.extend(fn(rel, text))
    return evidence


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser(description="Extract agnostic domain-logic evidence from a province.")
    ap.add_argument("root", nargs="?", default=".")
    args = ap.parse_args()
    ev = ingest(args.root)
    print(json.dumps([e.to_dict() for e in ev], indent=2))


if __name__ == "__main__":
    main()
