#!/usr/bin/env python3
"""
Autonomous Skill Synthesizer — Phase 14: The Autonomous Skill Factory & FTS5 Cache.

Analyzes Python files via AST to detect standalone utility functions and classes,
then synthesizes them into self-contained CLI skills registered under
.claude/skills/.

A node is "standalone" if it has no global statements and does not reference
other user-defined top-level functions or classes — i.e., it depends only on
its own arguments, builtins, and stdlib imports, not on module-level user state.

Each synthesized skill is immediately executable as a standalone tool by any
Tier 5 Squad or T6 Drone.

Inputs:  Any Python source file(s)
Output:  .claude/skills/<skill_name>.py
"""


import argparse
import ast
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).parent.parent.resolve()

_SKILL_TEMPLATE = """\
#!/usr/bin/env python3
\"\"\"
{skill_name} — Auto-synthesized SOVEREIGN-IMPERIA-CITADEL skill.

Generated by skill_synthesizer.py. Can be run as a standalone CLI tool
by any Tier 5 Squad or T6 Drone.
\"\"\"

import argparse
import sys


# --- Synthesized skill code ---
{source_code}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="{skill_name} skill")
    parser.add_argument("--input", metavar="TEXT", help="Input to process")
    args = parser.parse_args()
    if args.input:
        print(f"Processing: {{args.input}}")
    else:
        parser.print_help()
        sys.exit(1)
"""


class SkillSynthesizer:
    """Detect standalone utilities and synthesize them as executable skill files."""

    def __init__(self, root_dir: Path | None = None) -> None:
        self.root = root_dir or _ROOT
        self.skills_dir = self.root / ".claude" / "skills"

    def analyze_commit_delta(self, file_paths: list[str]) -> list[dict[str, Any]]:
        """Parse Python files and return standalone top-level functions/classes.

        Args:
            file_paths: Paths to Python files to analyze.

        Returns:
            List of dicts with keys: name, type, file, lineno, source, standalone.
            Dicts with an "error" key indicate unparseable files.
        """
        results: list[dict[str, Any]] = []
        for raw_path in file_paths:
            path = Path(raw_path)
            try:
                source = path.read_text(encoding="utf-8")
                tree = ast.parse(source, filename=str(path))
            except (OSError, SyntaxError) as exc:
                results.append({"file": str(path), "error": str(exc)})
                continue

            module_top_names: set[str] = {
                node.name
                for node in tree.body
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
            }

            source_lines = source.splitlines(keepends=True)

            for node in tree.body:
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    continue
                node_source = "".join(source_lines[node.lineno - 1 : node.end_lineno])
                results.append(
                    {
                        "name": node.name,
                        "type": type(node).__name__,
                        "file": str(path),
                        "lineno": node.lineno,
                        "source": node_source,
                        "standalone": self._is_standalone(node, module_top_names),
                    }
                )

        return results

    @staticmethod
    def _is_standalone(
        node: ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef,
        module_top_names: set[str],
    ) -> bool:
        """True if the node contains no global statements and does not reference
        other user-defined top-level names by Name lookup."""
        other_top_names = module_top_names - {node.name}
        for child in ast.walk(node):
            if isinstance(child, ast.Global):
                return False
            if isinstance(child, ast.Name) and child.id in other_top_names:
                return False
        return True

    def synthesize_and_register(self, skill_name: str, source_code: str) -> bool:
        """Write source_code as a self-contained CLI skill under self.skills_dir.

        Args:
            skill_name: Filename stem for the skill (e.g. "parse_json").
            source_code: Extracted utility code to embed in the template.

        Returns:
            True on successful write, False on OSError.
        """
        try:
            self.skills_dir.mkdir(parents=True, exist_ok=True)
            skill_path = self.skills_dir / f"{skill_name}.py"
            content = _SKILL_TEMPLATE.format(
                skill_name=skill_name,
                source_code=source_code.rstrip(),
            )
            skill_path.write_text(content, encoding="utf-8")
            skill_path.chmod(0o755)
            return True
        except OSError as exc:
            print(f"SkillSynthesizer: write failed — {exc}", file=sys.stderr)
            return False


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SOVEREIGN-IMPERIA-CITADEL Autonomous Skill Synthesizer")
    parser.add_argument(
        "--extract",
        metavar="FILE",
        nargs="+",
        help="Analyze Python file(s) and print detected standalone skills as JSON",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run hermetic self-test in an ephemeral temp directory",
    )
    args = parser.parse_args()

    if args.test:
        with tempfile.TemporaryDirectory() as _tmp:
            tmp = Path(_tmp)
            (tmp / ".claude" / "skills").mkdir(parents=True)

            dummy_src = tmp / "dummy_utils.py"
            dummy_src.write_text(
                "def format_number(value: float, precision: int = 2) -> str:\n"
                '    """Round and format a float as a fixed-precision string."""\n'
                '    return f"{value:.{precision}f}"\n',
                encoding="utf-8",
            )

            synthesizer = SkillSynthesizer(root_dir=tmp)
            detected = synthesizer.analyze_commit_delta([str(dummy_src)])
            assert detected, "No skills detected from dummy file"

            standalone = [d for d in detected if d.get("standalone")]
            assert standalone, f"Expected at least one standalone skill; got: {detected}"

            hit = standalone[0]
            assert hit["name"] == "format_number", f"Unexpected name: {hit['name']}"

            ok = synthesizer.synthesize_and_register(hit["name"], hit["source"])
            assert ok, "synthesize_and_register returned False"

            skill_file = tmp / ".claude" / "skills" / "format_number.py"
            assert skill_file.exists(), "Skill file was not written"

            skill_text = skill_file.read_text(encoding="utf-8")
            assert "format_number" in skill_text, "Skill name missing from generated file"
            assert "if __name__" in skill_text, "argparse block missing from generated file"
            assert "argparse" in skill_text, "argparse import missing from generated file"

            ok2 = synthesizer.synthesize_and_register(hit["name"], hit["source"])
            assert ok2, "Second synthesize_and_register returned False"

            print("SkillSynthesizer --test passed.")
        sys.exit(0)

    if args.extract:
        _synthesizer = SkillSynthesizer()
        _results = _synthesizer.analyze_commit_delta(args.extract)
        print(json.dumps(_results, indent=2))
        sys.exit(0)

    parser.print_help()
    sys.exit(1)
